### ISSUE TITLE
Some props to edit css of dropdown menu

### ISSUE THREAD

**Issue by francisrod01** [grizzthedj/react-bootstrap-dropdown-menu#2]
I think that I should be able to pass some props to dimensions of image.

* The `separator` is very large.
* The menu could've a `fadeIn` effect or `mouseOn`.
* A `carret` and a white `arrow` as github dropdown menu.
* Dimensions to image, because Social Media pass this to us.

![image](https://user-images.githubusercontent.com/4691768/33809003-c9a33d4e-ddd6-11e7-9cf8-56ff8fe2c304.png)

I think we can make it better like github dropdown-menu:

![image](https://user-images.githubusercontent.com/4691768/33949012-780c2b54-e00f-11e7-8d18-310e8604e9a8.png)

**Comment by grizzthedj** [comment]
@francisrod01 - Agree on the `separator`, and a `fadeIn` would be cool too. There is a `carat` when you use `triggerType='text'`, but not for images. Makes sense to have it there for image as well, and perhaps allow colour as well.

Will try to find some time over the next few weeks.

**Comment by francisrod01** [comment]
@grizzthedj thank you for answer me!!
I'll appreciate this PR. :)

**Comment by francisrod01** [comment]
I update the suggestion.
@grizzthedj thank you for answer me!!
I'll appreciate this PR. :)

**Comment by grizzthedj** [comment]
@francisrod01: I have pushed most of these changes. See the [CHANGELOG](https://github.com/grizzthedj/react-bootstrap-dropdown-menu/blob/master/CHANGELOG.md) for specific changes. I did not implement the `fadeIn` effect(yet), but will try to do so in coming weeks. 

Use this command to update your current version to 1.1.13

`npm update react-bootstrap-dropdown-menu --save`

**Comment by francisrod01** [comment]
Thank you @grizzthedj !! It's awesome now! :1st_place_medal: 
I think the `carat` should be toggle up/down arrow.

**Comment by grizzthedj** [comment]
Actually, the `carat` never toggled the up/down arrow even before, so no, it won't toggle. I can add this when I work on the `fadeIn` stuff.

**Comment by francisrod01** [comment]
Great job until now, @grizzthedj !! I love it! :)

**Comment by grizzthedj** [comment]
@francisrod01: I found some time this morning to do these changes(fade in and carat toggling). Version 1.1.14 is pushed. Going to close this ticket now. 

`npm update react-bootstrap-dropdown-menu --save`
