### ISSUE TITLE
Having issues if you created more than one dropdown

### ISSUE THREAD

**Issue by solomonbelda** [grizzthedj/react-bootstrap-dropdown-menu#3]
I have a **loop statement**, in every loop I am creating a dropdown menu. Whenever I click one of the dropdown menus it always trigger the first one, it opens the menu items of the first dropdown menu. Is it possible to create many instances of this dropdown in the same page?

**Comment by grizzthedj** [comment]
@solomonbelda - Thanks for using this tool! This is a known issue. I will try to push a fix for this in the next week or so(or sooner if I can).

**Comment by grizzthedj** [comment]
@solomonbelda - I have pushed this fix in 1.1.15. Added an example page as well: https://grizzthedj.github.io/react-bootstrap-dropdown-menu/demo/public/#/multiple

You can upgrade with ...

`npm upgrade react-bootstrap-dropdown-menu --save`

**Comment by solomonbelda** [comment]
Thanks man!
